repos:
  -   repo: https://github.com/sqlfluff/sqlfluff
      rev: 3.2.5
      hooks:
        - id: sqlfluff-lint
          name: Lint SQL files
          files: \.sql$
          
        - id: sqlfluff-fix
          name: Format SQL files
          files: \.sql$
